#!/bin/bash

sudo pacman -S flatpak

# FLATHUB
sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo &&

sudo pacman -Syu --noconfirm &&
sudo pacman -S --needed btop flatpak curl --noconfirm &&

# WORK
flatpak install -y flathub com.vscodium.codium &&
flatpak install -y flathub org.filezillaproject.Filezilla &&
flatpak install -y flathub org.remmina.Remmina &&
flatpak install -y flathub com.bitwarden.desktop &&
flatpak install -y flathub io.ente.auth &&

# UTILITIES
flatpak install -y flathub org.localsend.localsend_app &&

# OTHERS
flatpak install -y flathub com.discordapp.Discord &&
flatpak install -y flathub com.spotify.Client &&
flatpak install -y flathub org.telegram.desktop &&
flatpak install -y flathub com.brave.Browser &&
flatpak install -y flathub com.google.Chrome &&
flatpak install -y flathub org.gimp.GIMP &&
flatpak install -y flathub org.atheme.audacious &&

# BASH STARSHIP
curl -sS https://starship.rs/install.sh | sh
eval "$(starship init bash)"
